// Repo-doc content rendering (#3000, part of the repo-doc generation roadmap #2993). Turns a `RepoProfile`
// (src/review/repo-profile.ts) into the markdown body of a generated AGENTS.md. Pure and deterministic: no
// GitHub calls, no AI, no timestamps besides the one already carried on the profile -- the PR-delivery module
// (src/github/repo-doc-pr.ts) owns everything about HOW the rendered content reaches a repo.
//
// FAILS CLOSED WITH THE PROFILE: a `present: false` profile (no RAG index yet) renders nothing (`null`), mirroring
// #2999's own fail-closed design -- there is no partial or placeholder AGENTS.md, only a real one or none at all.
import type { RepoProfile, RepoProfileCommands, RepoProfileFileNamingStyle, RepoProfileTestFileConvention } from "./repo-profile";

/** Bumped whenever the RENDERED CONTENT's structure changes in a way #3004's diff-aware refresh needs to know
 *  about (new section, reordered section, changed marker) -- not on copy-only wording tweaks. */
export const REPO_DOC_TEMPLATE_VERSION = 1;

/** HTML-comment marker embedded in every generated AGENTS.md, mirroring the PR-panel marker convention
 *  (src/github/comments.ts's `PR_PANEL_COMMENT_MARKER`) so a future diff-aware refresh (#3004) can recognize
 *  "this file was machine-generated by Gittensory" without depending on exact prose. */
export const REPO_DOC_CONTENT_MARKER = `<!-- gittensory-repo-doc:v${REPO_DOC_TEMPLATE_VERSION} -->`;

const MAX_RENDERED_TOP_LEVEL_DIRECTORIES = 12;

const FILE_NAMING_STYLE_LABELS: Record<RepoProfileFileNamingStyle, string> = {
  "kebab-case": "kebab-case (`my-file.ts`)",
  camelCase: "camelCase (`myFile.ts`)",
  snake_case: "snake_case (`my_file.ts`)",
  PascalCase: "PascalCase (`MyFile.ts`)",
  mixed: "mixed -- no single dominant style detected",
  unknown: "not detected",
};

const TEST_FILE_CONVENTION_LABELS: Record<RepoProfileTestFileConvention, string> = {
  "dot-test-suffix": "`*.test.*` files",
  "dot-spec-suffix": "`*.spec.*` files",
  "tests-directory": "a `tests/`/`__tests__/` directory",
  "none-detected": "not detected",
};

function renderCommandList(label: string, commands: string[], packageManager: RepoProfileCommands["packageManager"]): string {
  if (commands.length === 0) return `- ${label}: none detected`;
  const runner = packageManager ?? "npm";
  const items = commands.map((name) => `\`${runner} run ${name}\``).join(", ");
  return `- ${label}: ${items}`;
}

function renderTopLevelDirectories(profile: Extract<RepoProfile, { present: true }>): string {
  const entries = profile.architecture.topLevelDirectories.slice(0, MAX_RENDERED_TOP_LEVEL_DIRECTORIES);
  const lines = entries.map((entry) => `- \`${entry.path}\` -- ${entry.fileCount} file${entry.fileCount === 1 ? "" : "s"}`);
  const omitted = profile.architecture.topLevelDirectories.length - entries.length;
  if (omitted > 0) lines.push(`- (${omitted} more, not shown)`);
  return lines.join("\n");
}

function renderCiWorkflowFiles(ciWorkflowFiles: string[]): string {
  if (ciWorkflowFiles.length === 0) return "- none indexed";
  return ciWorkflowFiles.map((path) => `- \`${path}\``).join("\n");
}

/**
 * Render the markdown body of a generated AGENTS.md from a repo profile, or `null` when the profile has no data
 * (`present: false`) -- callers must treat `null` as "do not generate", not as an empty-but-valid document.
 */
export function renderRepoDocContent(profile: RepoProfile): string | null {
  if (!profile.present) return null;
  const { architecture, conventions, commands, contributionWorkflow } = profile;
  return `# AGENTS.md

${REPO_DOC_CONTENT_MARKER}

This file is generated by [Gittensory](https://gittensory.aethereal.dev) from a profile of this repository's own
code -- it is not hand-written and not a generic template. If a fact below doesn't fit, edit this file directly.

## Architecture

${architecture.indexedFileCount} indexed source file${architecture.indexedFileCount === 1 ? "" : "s"} across ${architecture.topLevelDirectories.length} top-level director${architecture.topLevelDirectories.length === 1 ? "y" : "ies"}:

${renderTopLevelDirectories(profile)}

## Conventions

- File naming: ${FILE_NAMING_STYLE_LABELS[conventions.fileNamingStyle]}
- Test files: ${TEST_FILE_CONVENTION_LABELS[conventions.testFileConvention]}

## Commands

- Package manager: ${commands.packageManager ?? "not detected"}
${renderCommandList("Build", commands.buildCommands, commands.packageManager)}
${renderCommandList("Test", commands.testCommands, commands.packageManager)}
${renderCommandList("Lint", commands.lintCommands, commands.packageManager)}

## Contribution workflow

- CI publishes a required check: ${contributionWorkflow.gatePublishesCheck ? "yes" : "no"}
- Linked-issue policy: ${contributionWorkflow.linkedIssuePolicy}
- Requires a linked issue: ${contributionWorkflow.requireLinkedIssue ? "yes" : "no"}
- CI workflow files:

${renderCiWorkflowFiles(contributionWorkflow.ciWorkflowFiles)}

---

Generated ${profile.generatedAt} from this repository's own indexed code. Regenerating replaces this file's
content but never the rest of the repository.
`;
}
